### ISSUE TITLE
osgi.enroute.web.simple.provider breaks when configuring the context path

### ISSUE THREAD

**Issue by dleangen** [osgi/osgi.enroute.bundles#14]
The osgi.enroute.web.simple.provider web service works fine with the default configuration, but when using on a different context path, it seems to break.

Steps to reproduce:

 * Configure HttpWhiteboardConstants.HTTP_WHITEBOARD_SERVLET_PATTERN to be something other than "/"
 * Run the XRay service
 * Observe that nothing appears on the screen

My observations...

On line 390 of [WebServer](https://github.com/osgi/osgi.enroute.bundles/blob/master/osgi.enroute.web.simple.provider/src/osgi/enroute/web/server/provider/WebServer.java):

			String path = rq.getRequestURI();

I believe that this is not correct. This assumes that the context is the root context. When that is not the case, code such as that on line 147 of [WebResources](https://github.com/osgi/osgi.enroute.bundles/blob/master/osgi.enroute.web.simple.provider/src/osgi/enroute/web/server/provider/WebResources.java) breaks:

		if (!path.startsWith(OSGI_ENROUTE_WEBRESOURCE))
			return null;

**Comment by pkriens** [comment]
Could you provide a patch? As I learned to use the servlets no OSGi where you basically always have the root context I am not sure how to adapt the code that it always works?

**Comment by dleangen** [comment]
Hmmm, I took a go at it, but just changing the context configuration seems to break a lot of things. Makes me wonder why it is configurable in the first place. :-)

Making it configurable leaves the impression that it should work on other contexts. So, either it should not be configurable (i.e. it is built and intended to work only in the root context), or it needs some rework by somebody who understands this code better than I do.

I want to own the root context, so if this bundle is only intended to work on the root context, then maybe I will need to find a different solution. Currently, I am reconfiguring the context of this bundle, and from my servlet forwarding requests when I want to, for instance, handle static resources. This solution works great for static resources, but breaks for webresources (and probably other things).

**Comment by dleangen** [comment]
I'll try to take another shot at making the servlet work with different configurations, but I don't have time in the immediate future.

BTW, are you able to tell me where this code comes from? Is this original code, or was it "inspired" from somewhere?

**Comment by pkriens** [comment]
I've written it from scratch, mostly from my experience with the old OSGi Http Service specification.

**Comment by dleangen** [comment]
Very interesting. Thank you, [Peter](@pkriens), for that bit of information.

So, as the person who most understands both the objective and the innards of this bundle, perhaps you could advise me.

For somebody who wants to "extend" the functionality (in my case by choosing to either handle a request myself or allow it to "fall through" to the default behaviour, would it be better to:

 * Appropriate the root context (like I tried), and subsequently move this servlet to a different context? (Which is what I originally proposed in this issue.)
 * Leave this servlet on the root context, but provide some kind of extendable processing hook, which could for instance return a boolean to let the servlet know if it should continue processing or not?
 * Or some other solution that I am not seeing?

**Comment by pkriens** [comment]
I guess I have to understand the actual problem you want to solve :-)

From the text I think you want to allow an enRoute application in an app server? Using the root context would conflict with other apps, that is why you want to move it to a specific path? This path is then the base for all enRoute code?

The assumption in the setup was that you would have access to the root. The enRoute model already allows many different applications to coexist and web servers are plenty and easy. I think the model is today more to have a nginx front or so and then dispatch to different servers: the infamous micro-services model. I am afraid that enRoute UI code has probably a lot of implicit dependencies on this model.

That said, the webresources model is of course hiding the actual location of the resources so it should be possible to move it. However, there needs to be an agreement between the enRoute application code and the webserver servlet. I assumed the root for this shared knowledge.

So could you elaborate what you want to achieve?

**Comment by dleangen** [comment]
Hi Peter. Thank you for entertaining this discussion.

Ok, I will explain the problem we are trying to solve. It is possible that there is a solution that I am not seeing.

Our business requires that we serve resources (static websites or applications) on behalf of various clients. Each client owns its own domain. One of the principal activities of each client is promotion and sales, and the business people feel that they want to be able to serve resources from the root context in order to communicate shorter URIs (example.com instead of server.example.com/blah/blah/path). Whether this is a misguided concept or not is somewhat irrelevant, as this is based on opinion anyway, and just happens to be the business requirement. So: we have different resources that we want to serve on the path / depending on the domain from which it comes.

Technically, since at this time we have a small deployment, and want to keep management of these different domains from within "The System" (and not in an external route/proxy like apache or squid or whatever), and also that it is preferable (at least at this time) to have one and only one "The System", the thought is that ALL requests would get routed to this ominous "The System".

This means that from within "The System", requests from the path / need to be routed to the correct resource (static website, application). Since oftentimes a resource is a static website, osgi.enroute.web.simple.provider is perfect for handling this type of request, but does not have the ability to correctly route the requests. We do not want to send redirects, and unless I am misunderstanding something, forwarding would not work in a servlet filter, so we need a servlet, and this servlet needs to "own" /. I would like to have osgi.enroute.web.simple.provider work correctly if a request gets routed to it, but I need upstream control from / to route the requests properly, because osgi.enroute.web.simple.provider may not be the correct servlet to service a request.

I hope this makes sense. :-)

**Comment by dleangen** [comment]
I am in the processes of actually reading the http and servlet specs in order to have a more meaningful discussion. :-)

May take a bit of time...

**Comment by pkriens** [comment]
Take your time. It is your problem :-) (Though it would be nice to have this feature.)

**Comment by dleangen** [comment]
Thanks for your patience, Peter. I skimmed over the HTTP and servlet specs in order to have a better base understanding.

My conclusions are:
 1. This bundle does indeed belong in the root context
 2. However, the bundle is trying to do too much on the “/“ path

The reason for (1) is because, it seems, this is a “basic” functionality that should be provided with a “good” OSGi web provider. It provides several very nice web container functionalities, but with an OSGi flavour:

 * Routing requests specific to an OSGi environment
 * Forwarding a */ path to */index.html
 * Providing a facility for static web resources / websites
 * Providing a facility for “webresources”
 * Providing a facility for plugin contributions

(I still have not yet fully understood the last one, but I’ll look into that at some point.)

The reason for (2), I explain more below.

All of the 5 functionalities above are very nice, and very useful. However, I feel that there is too much crammed into one servlet. If these functionalities were each separated out, it would give the application/framework developer more fine-grained control. I could identify two ways to achieve this.

One simple way to “partition” the functionalities would be to update the HttpWhiteboardConstants.HTTP_WHITEBOARD_SERVLET_PATTERN property to contain a list of patterns for each of these functionalities, i.e.:

 * “/“ for the index redirector
 * Something like “/bnd” for static resources / websites
 * “/osgi.enroute.webresource” for webresources
 * “/osgi.enroute.contributions” for contributions (I am guessing)

In other words, any request ending with “/“ would (unless caught by a different filter/servlet) get routed to the index redirector, any request matching the path “/bnd” would serve up a static resources from the provided bundle Symbolic-Name, any request starting with “/orgi.enroute.webresource” would serve up a web resource, etc. For these functionalities to be more useful, they would have to be made available to the outside world at a consistent URI path. It is mainly for this reason that, after all, it is not a good idea to put this servlet anywhere other than in the default root context. Doing so would change the URI at which the functionalities are available, which would break (just like the original problem I noticed for XRay when I tried to change).

In my case, (except for the change that would be required to make static resources available over “/bnd” instead of “/“), I think that all I would need to do is update the HttpWhiteboardConstants.HTTP_WHITEBOARD_SERVLET_PATTERN in the configuration and omit the “/“ entry so I could appropriate “/“. I gave it a quick test run, and it seems to work as a solution.

Another (perhaps better) approach would be to actually split out each of the 5 functionalities into their own servlets. That way, if a user wants to provide their own implementation for any single one functionality, they would not have to throw out the baby with the bathwater, and get rid of the whole implementation. It would provide a more fine-grained approach. Perhaps each of these “functionalities” could start a trend in terms of the basis utilities that a good web provider should offer. Maybe it is even the right level of granularity for a modular web provider. But let’s not get out of hand just yet… :-)

In any case, the idea of this bundle is great, and very useful! That is why I want to be able to continue to use it. To make it even more useful, I think it would help to make it more fine-grained in one of the two ways mentioned (preferably the latter, though it would take some extra work).

What do you think?

**Comment by dleangen** [comment]
While awaiting your comment, I went ahead and tested the first (easiest) method, and it appears to work very well. I will submit a patch, and I suppose the discussion will move over there until resolution.

**Comment by pkriens** [comment]
As said on the PR, I like the idea of splitting the servlet. I see a servlet for the webresources/contributions but I think the /index.html and static access require /. The /index.html because then it is easy to override in a bundle and the static resources mapping from / should not contain a name like 'bnd'. I think static resources should use long names but mapped from the root.

**Comment by dleangen** [comment]
Agree for /index.html.

For static resources, how about just making the context part configurable? That way if you want to use root, you can, but if you want to use something else, that's ok, too. :-)

**Comment by pkriens** [comment]
The problem is then that an enRoute bundle can not rely on this which will make reusability a problem :-( Each bundle would have to take this variability into account. 

I am actually not sure I understand where you run into problems with the / servlet? It should normally only catch the URIs that are not yet occupied by another servlet? Only when some other servlet wants to use the root would you get problems?

**Comment by dleangen** [comment]
Hmmmm. That is true, unfortunately.

Right about root: it is because I want to be able to occupy root. That is how the whole issue got started in the first place. :-) 

Perhaps if somebody wants to occupy root and use this servlet as a fall-through, this servlet could just be wrapped with the root-occupying servlet. In the case of a fall-through, then super.doGet() would do the trick. The only thing I don't like is having to depend on the implementation, but if it gets the job done...

**Comment by pkriens** [comment]
Can you tell me what your use case? I have no problem creating a service that allows us to chain 'root' handlers. The problem with the Servlet API is that it does not allow you tell the engine that you could not find it but somebody else should have a go ... We could make it so that it is a servlet that will get invoked in the order of servlet ranking?

**Comment by dleangen** [comment]
Thanks Peter. I actually already explain it [on this very comment page](https://github.com/osgi/osgi.enroute.bundles/issues/14#issuecomment-172529135), so I won't repeat everything here.

In essence, though, because of the way we handle URIs in URI Space, I need to have a front-end router to route requests. The URI processing is a bit too complex for just simply registering via OSGi; I need some active and dynamic processing power. In the cases where I actually do not want to forward to a custom servlet to handle a request, I would like to allow the request to fall through to the enRoute Web Provider for "default" behaviour.

The idea of chaining sounds great. In the case where my servlet decides that it does not need to route the request, then I can pass it on to the next servlet in the chain, i.e. the enRoute Web Provider. It would have to be done dynamically, though, as my servlet would still need to inspect each request.

**Comment by pkriens** [comment]
So what is your preference?

* A ROOT_SERVLET property on an HTTP servlet. Since the service method returns void you would have to throw some exception if you won't handle it.
* A dedicated enRoute service API (which we might standardize in the OSGi)

        public interface RootServlet  {
            boolean doService( HttpServletRequest rq, HttpServletResponse rsp );
        }

**Comment by dleangen** [comment]
Nice! IIUC what you are proposing, I like the second approach. Sounds like an elegant way to handle this problem, and would easily allow good control, including chaining. Very nice!

**Comment by dleangen** [comment]
BTW, sorry I didn't notice this before...

How does "doService" relate to GET, POST, et al? On that note, I noticed that the enRoute service only handles GET. Is there a reason for that?

**Comment by pkriens** [comment]
in doService you call super.service(...) with the given parameters after you decided to accept the path. the service() method calls post, get etc.

**Comment by dleangen** [comment]
Ah, yes, of course! There is no need to separate into doGet() etc. in HttpServlet, as the parent GenericServlet does that in service().. I see what you mean. That is perfect.

**Comment by pkriens** [comment]
I've added https://github.com/osgi/osgi.enroute/tree/master/osgi.enroute.base.api/src/osgi/enroute/rootservlet/api

The next piece of work is to create:

* A Default servlet that registers at / and then dispatches to the RootServlet (should always run)
* The bundle-static access bundle
* The web resources bundle

You want to take a stab?

**Comment by dleangen** [comment]
Hi Peter, I'll give it a stab. We'll see if that does more harm than good. :-)  (Reminds me of "Hotel California": "They stab it with their steely knives, but they just can't kill the beast.")

One problem: to set up a development environment, I am trying to "release" the packages in the osgi.enroute workspace so I can create a local repo and refer to it from osgi.enroute.bundles, but nothing happens when I run "gradle release" (nor when I try to release from the menu in Eclipse). Does something different happen in this workspace?

**Comment by pkriens** [comment]
In enRoute I handle the release manually at the moment. We have to set up the release chain.

Why not just checkout the osgi.enroute.bundles project and work in there?

**Comment by dleangen** [comment]
That's what I'm doing :-) but the [Distro repo](https://raw.githubusercontent.com/osgi/osgi.enroute/master/cnf/distro/index.xml) is not pointing to the updated version that contains the RootServer interface. I am temporarily working around this by copying/pasting the interface in the implementation bundle, but that is obviously a temporary solution.

**Comment by dleangen** [comment]
In any case, I'll be honest with you. I am having a tough time with this code. I have tried a few different approaches to coax out the different functionalities into separate servlets. The code seems to work very well as currently packaged, but there seem to be too many interdependencies to cleanly extract out the parts. Since you made this code, probably what you intended (and the way to separate out the different functionalities) may be clearer to you. I really hate to give up, and I would like to help out, but I think I'm just making a mess of things trying to reuse this code. :-( I suppose I could redesign the code completely, but I don't think that's what you're after, either.

**Comment by pkriens** [comment]
Ok, I can have a stab at it.

**Comment by pkriens** [comment]
Why not for now just implement the RootServlet behavior in the single servlet? Know that is the wrong direction but it works immediately :-) Just a short loop over the RootServlet services in the service method.

**Comment by dleangen** [comment]
Ok, I'll have a look at that. :-)

**Comment by dleangen** [comment]
Created [PR #18](https://github.com/osgi/osgi.enroute.bundles/pull/18).
