### ISSUE TITLE
ExceptionFilter in WebServer

### ISSUE THREAD

**Issue by dleangen** [osgi/osgi.enroute.bundles#29]
What is the [ExceptionFilter](https://github.com/osgi/osgi.enroute.bundles/blob/master/osgi.enroute.web.simple.provider/src/osgi/enroute/web/server/provider/ExceptionFilter.java) (and corresponding exceptions configuration) for?

Is it still being used, or can it also go in the spring cleaning?

**Comment by pkriens** [comment]
It prints out the exception if activated. It might also be one of this 'good ideas' I had. I guess it is not used anywhere (yet)?

**Comment by dleangen** [comment]
:-)

I did not see it used anywhere. Would you mind if I included it in Spring Cleaning?? (If somebody asks for it, should be easy to bring back.)

**Comment by pkriens** [comment]
Go ahead!
