### ISSUE TITLE
404 handling

### ISSUE THREAD

**Issue by dleangen** [osgi/osgi.enroute.bundles#30]
A few questions...

1. What is the expectation regarding whether or not a bundle contains a 404.html file?
2. What is the default folder? (I couldn't find it anywhere [though my search was not entirely exhaustive, either]).

Example from [WebServer](https://github.com/osgi/osgi.enroute.bundles/blob/master/osgi.enroute.web.simple.provider/src/osgi/enroute/web/server/provider/WebServer.java#L553):

    FileCache do404(String path) throws Exception {
		log.log(LogService.LOG_INFO, "404 " + path);
		FileCache c = findBundle("404.html");
		if (c == null)
			c = findBundle("default/404.html");
		if (c != null)
			c.is404 = true;

		return c;
	}

**Comment by pkriens** [comment]
It was added but so far never used by me. Looking at the code it should reside in /static/default/404.html.

**Comment by dleangen** [comment]
Is the idea that this would be displayed if the user did not configure a 404 using the `osgi.http.whiteboard.servlet.errorPage` property?

If so, then shouldn't we first check to see if that property was set or not?

Or perhaps I'm not understanding the intent?

**Comment by pkriens** [comment]
This was done before the new OSGi Http spec. (This code is 5 years old.)I am not that crazy about a property for this since it is much easier to provide these pages statically. Then again, maybe it is a separation of concerns. 

I am ok go check if the property is set.

**Comment by dleangen** [comment]
Thanks, Peter. I have a few ideas I'll try out.
