### ISSUE TITLE
Purpose of Enroute-Application

### ISSUE THREAD

**Issue by dleangen** [osgi/osgi.enroute.bundles#31]
Hi!

I am questioning the purpose of the Enroute-Application here.

Yes, it provides a neat index for demo purposes, but other than that, what value does it add for developers?

Could we consider moving it to the examples workspace instead of keeping it here?

Or am I missing something?

**Comment by pkriens** [comment]
Well, I am open for other suggestions but beause we use long unique paths for the application, without it it is hard. But it would be nice if it was configurable.

**Comment by dleangen** [comment]
> beause we use long unique paths for the application, without it it is hard

Are you able to tell me more precisely what problem you are trying to solve? What is hard?

**Comment by pkriens** [comment]
If you're debugging you have to recall that long name. Especially with demos it sucks because you're trying to figure out where what is. So I really need the feature.
