### ISSUE TITLE
osgi.enroute.gogo.shell.provider v1.0 not working on win7

### ISSUE THREAD

**Issue by tonit** [osgi/osgi.enroute.bundles#34]
is this supposed to work on windows?
I see:

> java.lang.NoClassDefFoundError: Could not initialize class org.fusesource.jansi.internal.Kernel32
        at org.fusesource.jansi.internal.WindowsSupport.getConsoleMode(WindowsSupport.java:50)
        at jline.WindowsTerminal.getConsoleMode(WindowsTerminal.java:203)
        at jline.WindowsTerminal.init(WindowsTerminal.java:81)
        at jline.TerminalFactory.create(TerminalFactory.java:120)
        at jline.TerminalFactory.get(TerminalFactory.java:184)
        at jline.TerminalFactory.get(TerminalFactory.java:190)
        at osgi.enroute.gogo.shell.provider.Shell$1.run(Shell.java:150)
        at java.lang.Thread.run(Thread.java:745)

**Comment by njbartlett** [comment]
You're probably the first to test it... I don't have access to a Windows box.

**Comment by tonit** [comment]
Sure. Will see what i can do. JLine2 itself seems to be a good OSGi citizen but the underlying jansi lib might be rough.

**Comment by pkriens** [comment]
Any progress?

**Comment by KonsolenJockey** [comment]
v2.0 is also not working on win7. I found out the this bundle embeds the jline library with a -conditionalpackage directive, but this library also contains shared libraries (.so/.dll 32/64bit versions) which is not included, wondering how this is working on linux and osx. if i extract the dll manually from that jar and put it on java.library.path the examples are working. so i think this is a repackaging issue. The solutions i see are eather depend on a jline library bundle or embed all of it correctly. but the -conditionalpackage is only meant for java packages, how do you embed the native library like in this case?

**Comment by pkriens** [comment]
You can use -includeresource but shouldn't we deprecate this one since Apache Felix now supports one? The OSGi enRoute bundles have always been intended to disappear because better ones become available in open source projects.

**Comment by njbartlett** [comment]
Agreed, let's deprecate. How do we do that?

**Comment by KonsolenJockey** [comment]
Just saw that there was a gogo shell 1.0 release, so let's deprecate this an close this issue.

**Comment by pkriens** [comment]
agree ...
