### ISSUE TITLE
Plugin Contributions

### ISSUE THREAD

**Issue by dleangen** [osgi/osgi.enroute.bundles#36]
I am finally getting close to having a presentable result. Just one more thing to look into: plugin contributions.

I don't quite understand what this is for, and I was not able to find any examples anywhere.

This is the only doc I could find, but unfortunately it's not quite enough for me to "get it".

```java
/**
 * This class creates a cached file that contains contributions from a set of
 * plugins. A bundle can register a service with the
 * {@link #PLUGIN} property. This must be a String+ identifying the
 * applications this plugin is part of. It should then set
 * {@value #CONTRIBUTIONS} with the paths to Javascript resources
 * that should be included. This class will then concatenate all these JS
 * resources into file. If the underlying plugins change then the file will be
 * refreshed.
 * <p>
 * A file that wants to use this model should define the following tags (the .js extension will be stripped if present):
 * <pre>
 * 	<script src="/osgi.enroute.contributions/my.app.js">
 * </pre>
 * This will then automatically include all 
 */
```

Any way of getting some additional info?

And of course my usual question: is this still needed?? :-)

**Comment by pkriens** [comment]
I like your attitude. 

The basic idea is that any bundle can contribute web resources to another bundle, without the other bundle being aware of it. However, I never got around to finish it. So kill it, I'll resurrect it when I have time.

**Comment by dleangen** [comment]
:-)

Ok, sure thing. Thanks, Peter.
