### ISSUE TITLE
osgi.enroute.web.simple.provider binds to servlet pattern "/"

### ISSUE THREAD

**Issue by njbartlett** [osgi/osgi.enroute.bundles#39]
I'm experimenting with RFP 171 Web Resources implementation. As far as I understand it, the bundle `osgi.enroute.web.simple.provider` is the extender that reads the `Provide-Capability: osgi.enroute.webresource` headers.

Unfortunately this bundle publishes a servlet with a path pattern of "/", meaning that it intercepts all requests, and interferes with all other servlets. Why does it need to do this? The resources are always accessed from a URL beginning with `/osgi.enroute.webresource` so it seems that the servlet should just use that pattern.

In general the web.simple.provider seems to be doing way more than just serving Web Resources. Can this be decoupled?

**Comment by pkriens** [comment]
This is already in progress by @dleangen, he had similar concerns.The functionality is now split up and it allows for servlets that 'try' to use the root space.

The functionality is necessary so that every bundle can contribute its /static directory that is then cached and merged.

**Comment by pkriens** [comment]
https://github.com/osgi/osgi.enroute.bundles/pull/28

**Comment by dleangen** [comment]
Hi Neil,

I have been working on exactly this problem. I expect to be finished with my PR soon.

In the PR, `/osgi.enroute.webresource` has its own servlet based on this path. Also, it provides a means to access the '/' path if you need it.

I was having the same issues, and needed a more configurable solution, so I took on this task myself.

**Comment by njbartlett** [comment]
Thanks David, sounds good.

This kind of thing helps to make enRoute less of an "all or nothing" proposition, which in turn makes it more useful for people who already have knowledge and investment in OSGi.

**Comment by njbartlett** [comment]
Closing since this is covered by #28
