### ISSUE TITLE
add .editorconfig to define coding styles for IDEs and editors

### ISSUE THREAD

**Issue by dpishchukhin** [osgi/osgi.enroute.bundles#41]
it can help to keep code format and minimize merging issues

more details: http://editorconfig.org/

as an example:

```
root = true

[*.{java,json,js,py,properties,htm,html,css,xml,bnd}]
end_of_line = lf
insert_final_newline = true
charset = utf-8
indent_style = space
indent_size = 4
```

**Comment by pkriens** [comment]
Sorry for not responding earlier. (I seem to ignore you more often :-( ). 

I am not sure I am ready to add this to since we're mostly Eclipse and I think I would prefer Eclipse formatting settings?

**Comment by dpishchukhin** [comment]
we can close it until I find a good example for this. I tried to edit with IDEA and gradle plugin and had issues with formatting. With Eclipse I don't have any issues. If all enRoute committers use Eclipse this issue is not relevant.
