### ISSUE TITLE
Configurer should use optional reference to Coordinator

### ISSUE THREAD

**Issue by njbartlett** [osgi/osgi.enroute.bundles#42]
IMHO the proper way to use Coordinator is as an optional service reference... if there is no coordinator service available then this equivalent to there being no current coordination.

If you agree I can make the change.

**Comment by pkriens** [comment]
Hmm. I wanted to make the Coordinator mandatory in OSGi enRoute because it is easy to set with a Filter. 

If the Coordinator is not mandatory, then you cannot assume it so you need an alternative, which basically voids the use of a coordinator in most use cases.

**Comment by njbartlett** [comment]
But the Configurer only creates a coordination while it makes the config changes. It doesn't *need* the batching, it only delimits batches because that may be convenient for another bundle.

**Comment by pkriens** [comment]
Ok, in this case it is true. Did not read the title correctly. Go ahead.

**Comment by pkriens** [comment]
Neil, can we close this?
