### ISSUE TITLE
Add Simple Encryptor Provider

### ISSUE THREAD

**Issue by kameshsampath** [osgi/osgi.enroute.bundles#43]
Add a Simple Text Encryptor provider based on http://www.jasypt.org/

**Comment by dleangen** [comment]
Is that link correct? I get a dead page...

**Comment by kameshsampath** [comment]
@dleangen are you asking about the bundle or the jasypt link i put in above ?

**Comment by dleangen** [comment]
Oh, never mind. The site is back up now. :-)
