### ISSUE TITLE
Migrate vaadin.examples to osgi.enroute.vaadin

### ISSUE THREAD

**Issue by florianpirchner** [osgi/osgi.enroute.bundles#49]
I migrated the enroute.vaadin.example to this repo. And i am nearly done.

Added metatype and config admin.

The bundles-structure:
- enroute.vaadin.api - Contains the Application, Configuartion-Annotation
- enroute.vaadin.dto - DTO for application config
- enroute.vaadin.provider - The provider and handler implementation from enroute.vaadin.example
- enroute.vaadin.example.addressbook - The addressbook sample
- enroute.vaadin.runtime - Extracted the DTOContainer and DTOItem to a bundle which may be consumed by applications during runtime
- enroute.vaadin.tests - The test classes

For now i am struggling with a bnd feature. If this issue is clarified, i am going to create a pull request.

Best Florian

**Comment by pkriens** [comment]
Any progress?

**Comment by florianpirchner** [comment]
Yep. I am nearly done.

Fighted with the config annotation for meta type and bnd tools. Got build
error.
But found a solution now.

This week I am at a customers side until tomorrow. Will finish during next
days.

Best florian

Peter Kriens <notifications@github.com> schrieb am Do., 14. Juli 2016 18:13:

**Comment by florianpirchner** [comment]
Dear Peter,

i got a question about my PR.

I also added CM support based on webconsole. But bndtools tells me, that something went wrong.

My ideas is:
Vaadin can be configured in serveral ways. ProductionMode, heartBeat, push-stuff, pageTitle,... 
Therefore i created a DTO {1}.

Application {2} now provides this DTO to the handler which wires the servlet stuff with the http service and configs.

And i have created a config annotation "Configuration" {3} (ObjectClassDefinition) and put it into the API bundle. For me it seems pretty perfect there. In my opinion the properties can be handled by vaadin. And a provider needs to handle them all.

Then i added @Designate(ocd = Configuration.class) to the AddressBookExampleApplication {4}.

But bndtools tells me "osgi.enroute.vaadin.example.addressbook.application: DS Component osgi.enroute.vaadin.example.addressbook.application.AddressbookApplication specifies ocd class osgi.enroute.vaadin.api.Configuration which cannot be found; known classes []"

I debuged this issue and found out, that the OCDReader (do not remember the name right now) in bndtools does not follow the ocd class in @Designate annotation.

So my question is:
Where should i put the ObjectClassDefinition annotation to? Should i put it into the example bundle? Then bndtools does not show any error.
But in my opinion, the API bundle would be a perfect place for it.

Thanks a lot for your time and input,
Florian

[1] https://github.com/florianpirchner/osgi.enroute.bundles/tree/master/osgi.enroute.vaadin/src/osgi/enroute/vaadin/dto
[2] https://github.com/florianpirchner/osgi.enroute.bundles/blob/master/osgi.enroute.vaadin/src/osgi/enroute/vaadin/api/Application.java
[3] https://github.com/florianpirchner/osgi.enroute.bundles/blob/master/osgi.enroute.vaadin/src/osgi/enroute/vaadin/api/Configuration.java
[4] https://github.com/florianpirchner/osgi.enroute.bundles/blob/master/osgi.enroute.vaadin/src/osgi/enroute/vaadin/example/addressbook/application/AddressbookApplication.java

**Comment by pkriens** [comment]
I think because of the metatype the class must be in the same bundle as the XML.

So you would have to make the API bundle contain the metatype. As long as you make sure the PIDs line up you can probably make that work. You can also have multiple pids on a component nowadays I think.

So you can likely get it right but sometimes it is more pragmatic to just put this in the application.

If you want to pursue the puristic approach I suggest you raise this on the Bndtools ist.

**Comment by florianpirchner** [comment]
Thanks
