### ISSUE TITLE
Add Support for Angular 1.5.x

### ISSUE THREAD

**Issue by kameshsampath** [osgi/osgi.enroute.bundles#54]
As there are lot of chnges form Angular 1.4.x to 1.5.x, we should add support for the angular 1.5.x to the angular web resource bundle

**Comment by pkriens** [comment]
Yes, it would be nice if that bundle was added.

Will you provide a PR? We can build the bundle and make it available over the Maven snapshots which are automatically build.

Kind regards,

	Peter Kriens

**Comment by kameshsampath** [comment]
I will send in the PR once I am done with JDBC example. 

 
-Kamesh

Date: Thu, 14 Jul 2016 09:06:42 -0700

**Comment by kameshsampath** [comment]
would you like to be a seperate bundle, or i can add the the required resources under the angular webresource bundle as 1.5.x?

**Comment by pkriens** [comment]
Just add them to the existing project. This should be self explanatory
