### ISSUE TITLE
osgi.enroute.rest.simple.provider: when set the corsEnabled is true, the server 500 error 

### ISSUE THREAD

**Issue by hwcompany** [osgi/osgi.enroute.bundles#75]
I check the source code, finded the possible reasons, config object is not set value in the RestServlet class, and there are the same problems in osgi.enroute.rest.simple.provider version 2.0.

**Comment by mcurcija** [comment]
I run into this one as well. The constructor does not set internal "config" field which causes NPE later in addCorsHeaders method.

The following re-factoring commit for RestServlet caused is responsible for NPE:
```
commit a43482d19971dc6ae174cbe00ef19f0fdb068f00
Minor update of documentation based on my new understanding of REST endpoint
```
Minimal patch: 
```
diff --git a/osgi.enroute.rest.simple.provider/src/osgi/enroute/rest/simple/provider/RestServlet.java b/osgi.enroute.rest.simple.provider/src/osgi/enroute/rest/simple/provider/RestServlet.java
index bca6a57..bb80989 100644
--- a/osgi.enroute.rest.simple.provider/src/osgi/enroute/rest/simple/provider/RestServlet.java
+++ b/osgi.enroute.rest.simple.provider/src/osgi/enroute/rest/simple/provider/RestServlet.java
@@ -39,6 +39,7 @@
 	final RestMapper			mapper;
 
 	RestServlet(Config config, String namespace) {
+		this.config = config;
 		corsEnabled = config.corsEnabled();
 		this.mapper = new RestMapper(namespace);
 	}

```

**Comment by pkriens** [comment]
Can you provide a PR?

**Comment by mcurcija** [comment]
Pull request #82 created. Sorry no unit/integration tests just applied patch.

**Comment by mcurcija** [comment]
The "corsEnabled" feature works now as expected since Pull request #82 was merged in master. This issue should be closed.
