### ISSUE TITLE
osgi.enroute.configurer.simple.provider gives service.bundleLocation="?"

### ISSUE THREAD

**Issue by eliasvasylenko** [osgi/osgi.enroute.bundles#80]
The settings are properly bound to the service according to the configurationPID, but the `service.bundleLocation` property is not properly set and just ends up as `?`.

This is in combination with the `org.apache.felix.configadmin` implementation if that's relevant.

I may have misunderstood as I don't know what purposes the property actually has internally, and everything does still seem to work, but shouldn't the bundle location be naturally derived from the service component and the property set accordingly?

If I remove the appropriate entry from the `configuration.json` file and save a configuration manually through the felix web console instead the behaviour is identical except that `service.bundleLocation` is set.

**Comment by Danipiario** [comment]
I think problem is in Configurer class at line 297.
Prior to bdffbc71e9726061a2a687b9952610da6483112e commit the code was
`configuration.setBundleLocation(null);`
I don't know where is the mistake, in Felix ConfigAdmin or in Configurer class

**Comment by pkriens** [comment]
The bundle location should today in almost all cases be set to '?', indicating that all bundles can use it.
